# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 268c194d9a58b02a7404a719aad21bfaf83b721b058944ff2b1d533531e422236999a53418547008ccec429fb7105e472e4ac0b012feb8128a90ef8498066f64

test:
  secret_key_base: 90cf7ef33111b0152b016bbb085b52ccc33dc5cc455622cd423eda8dfb5cccbad84ae8158486c7a004b0afb12c86b0d467fd2236cd3a75628c3e01c0c044dea8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
